var inPlace = new InPlace();
inPlace.GenerateNumbers(1, 100);
Console.WriteLine(inPlace.CalculateSum());
inPlace.InsertSumAfterPairs();
Console.WriteLine(inPlace.CalculateSum());
inPlace.RemoveEvenNumbers();
Console.WriteLine(inPlace.CalculateSum());
inPlace.ReplaceWithRunningTotal();
Console.WriteLine(inPlace.CalculateSum());
long result = inPlace.CalculateResult();
Console.WriteLine($"Result: {result}");

var list = NewList.GenerateNumbers(1, 100);
Console.WriteLine(NewList.CalculateSum(list));
list = NewList.InsertSumAfterPairs(list);
Console.WriteLine(NewList.CalculateSum(list));
list = NewList.RemoveEvenNumbers(list);
Console.WriteLine(NewList.CalculateSum(list));
list = NewList.ReplaceWithRunningTotal(list);
Console.WriteLine(NewList.CalculateSum(list));
result = NewList.CalculateResult(list);
Console.WriteLine($"Result: {result}");
